# -*- coding: utf-8 -*-
"""boot day7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeZGbtlxXrfZYwCZd_cbJZL1c-p-vBw9
"""

!pip install optuna

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,precision_score,recall_score,f1_score,confusion_matrix,ConfusionMatrixDisplay,roc_curve,roc_auc_score
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

data=load_breast_cancer(as_frame=True)
df=data.frame

df.head()

X=df.drop('target',axis=1)
y=df['target']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

rf=RandomForestClassifier()
rf.fit(X_train,y_train)
rf_pred=rf.predict(X_test)

print('Accuracy Score: ',accuracy_score(y_test,rf_pred))
print('Classification report:\n ',classification_report(y_test,rf_pred))

xgb=XGBClassifier()
xgb.fit(X_train,y_train)
xgb_pred=xgb.predict(X_test)

print('Accuracy Score: ',accuracy_score(y_test,xgb_pred))
print('Classification report:\n ',classification_report(y_test,xgb_pred))

lbm=LGBMClassifier()
lbm.fit(X_train,y_train)
lbm_pred=lbm.predict(X_test)

print('Accuracy Score: ',accuracy_score(y_test,lbm_pred))
print('Classification report:\n ',classification_report(y_test,lbm_pred))

compare=pd.DataFrame({
    'model': [
        'Random Forest',
        'XGBoost',
        'LightGBM'
    ],
    'accuracy_score': [
        accuracy_score(y_test,rf_pred),
        accuracy_score(y_test,xgb_pred),
        accuracy_score(y_test,lbm_pred)
    ]
})
display(compare)

precision=precision_score(y_test,rf_pred)
recall=recall_score(y_test,rf_pred)
f1=f1_score(y_test,rf_pred)

print('Precision Score: ',precision)
print('Recall Score: ',recall)
print('F1 Score: ',f1)

cm=confusion_matrix(y_test,rf_pred)
disp=ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=rf.classes_)
disp.plot(cmap='Blues')
plt.title('Confusion Matrix')
plt.show()

y_porb=rf.predict_proba(X_test)[:,1]
roc_score=roc_auc_score(y_test,y_porb)
print('ROC AUC Score: ',roc_score)

fpr ,tpr , thresholds = roc_curve(y_test,y_porb)
plt.figure(figsize=(8,6))
plt.plot(fpr,tpr,label=f"AUC {roc_score}")
plt.plot([0,1],[0,1],linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend()
plt.show()

from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
import optuna

model = XGBClassifier(random_state=42).fit(X_train,y_train)
y_pred = model.predict(X_test)
print('Baseline Accuracy: ',accuracy_score(y_test,y_pred))

param_grid={
    'n_estimators':[100,200,300],
    'max_depth':[3,4,5],
    'learning_rate':[0.01,0.1,0.2]
}

grid=GridSearchCV(
    estimator=XGBClassifier(random_state=42),
    param_grid=param_grid,
    cv=5,
    scoring='accuracy'
).fit(X_train,y_train)

print('Best Parameters: ',grid.best_params_)
best_model=grid.best_estimator_
y_pred=best_model.predict(X_test)
print('Accuracy Score: ',accuracy_score(y_test,y_pred))

random_params={
    'n_estimators':[50,100,150,200],
    'max_depth':[3,4,5,6,7],
    'learning_rate':[0.01,0.05,0.1,0.2]
}

random_search=RandomizedSearchCV(
    estimator=XGBClassifier(random_state=42),
    param_distributions=random_params,
    n_iter=10,
    cv=5,
    random_state=42
).fit(X_train,y_train)

print('Best Parameters: ',random_search.best_params_)
best_model=random_search.best_estimator_
y_pred=best_model.predict(X_test)
print('Accuracy Score: ',accuracy_score(y_test,y_pred))

import optuna
def objective(trial):
  model = XGBClassifier(
      n_estimators=trial.suggest_int('n_estimators',50,300),
      max_depth=trial.suggest_int('max_depth',3,7),
      learning_rate=trial.suggest_float('learning_rate',0.01,0.2),
      random_state=42
  )
  model.fit(X_train,y_train)
  y_pred=model.predict(X_test)
  return accuracy_score(y_test,y_pred)

study=optuna.create_study(direction='maximize')
study.optimize(objective,n_trials=20)
print('Best Parameters: ',study.best_params)

best_model=XGBClassifier(**study.best_params,random_state=42)
best_model.fit(X_train,y_train)
y_pred=best_model.predict(X_test)
print('Accuracy Score: ',accuracy_score(y_test,y_pred))

from imblearn.over_sampling import RandomOverSampler
ros=RandomOverSampler(random_state=42)
x_sample,y_sample=ros.fit_resample(X_train,y_train)

from imblearn.under_sampling import RandomUnderSampler
rus=RandomUnderSampler(random_state=42)
x_sample,y_sample=rus.fit_resample(X_train,y_train)

from imblearn.over_sampling import SMOTE
smote=SMOTE(random_state=42)
x_sample,y_sample=smote.fit_resample(X_train,y_train)

from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(class_weight='balanced')
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

ratio=len(y_train[y_train==0])/len(y_train[y_train==1])
model=XGBClassifier(scale_pos_weight=ratio,random_state=42)
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

prob=model.predict_proba(X_test)[:,1]
thresholds=0.40
prediction=(prob>thresholds).astype(int)
for thresholds in [0.5,0.4,0.2]:
  prediction=(prob>thresholds).astype(int)
  print(precision_score(y_test,prediction))

import shap
explainer=shap.TreeExplainer(model)
shap_values=explainer.shap_values(X_test)
shap.summary_plot(shap_values,X_test,feature_names=X_test.columns)

shap.initjs()
shap.force_plot(
    explainer.expected_value,
    shap_values[0:],
    X_test.iloc[0:],
    feature_names=X_test.columns
)

